#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=roberta_job
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --time=10:00:00
#SBATCH --mem=32000M
#SBATCH --array=1-40%2
#SBATCH --output=job_outputs/roberta_%A_%a.out

module purge
module load 2019
module load Python
module load Anaconda3

source activate atcs-project

PARAMETERS_FILE=h_search.txt

srun python -u train.py $(head -$SLURM_ARRAY_TASK_ID $PARAMETERS_FILE | tail -1)
